list_container: "div.elementor-posts-container"
card_selectors: "article.elementor-post"
title_selectors:
  - "h3.elementor-post__title > a"
  - ".elementor-post__title > a"
url_selectors:
  - "h3.elementor-post__title > a@href"
  - ".elementor-post__read-more@href"
  - "a.elementor-post__thumbnail__link@href"
image_selectors:
  - ".elementor-post__thumbnail img@data-src"
  - ".elementor-post__thumbnail img@srcset"
  - ".elementor-post__thumbnail img@src"
date_selectors:
  - "span.elementor-post-date"
  - ".elementor-post__meta-data span"
text_selectors:
  - ".elementor-post__excerpt p"
  - ".elementor-post__excerpt"
next_page_link:
  - "nav.elementor-pagination a.next"
  - "a.page-numbers.next@href"
  - ".elementor-pagination a.next@href"